### PR TITLE
ship dependencies

### PR DESCRIPTION
**Pull request by manelclos**

### CODE REVIEW

**Comment by mangelats** [comment]
`requests` and  `SecretStorage` are missing, aren't they?

**Comment by manelclos** [comment]
Is if failing in linux because those packages are not available? it works in windows and mac, maybe because the packages were already installed...

**Comment by mangelats** [comment]
I have them installed but i had to manually do so at the start of the project. I'll make a virtual machine and try it out.

**Comment by mangelats** [comment]
Actually, they are not listed in the [documentation](https://docs.python.org/3/library/index.html). So we should add them.

**Comment by manelclos** [comment]
Great, let me know the outcome.

**Comment by mangelats** [comment]
Ok. A freshly installed Ubuntu 18.04 LTS already had `python3` installed by default. Also `requests` and `keyring` were included. `SecretStorage` should be for `keyring` in some OS so it is not included (I think it was for Windows). So technically we might not even need this branch (for Ubuntu, at least).

**Comment by manelclos** [comment]
Does it work on Linux with the dependencies we ship so it works on Windows?

**Comment by mangelats** [comment]
The `win32ctypes` breaks it.

**Comment by manelclos** [comment]
Can you paste the error here?

**Comment by mangelats** [comment]
I actually don't expect that module to work on linux. It is obviously a Windows module.

<details>
<summary>Here is the error:</summary>

```
Couldn't load plugin 'giscube-admin-qgis-plugin' due to an error when calling its classFactory() method 

ValueError: _type_ 'v' not supported 
Traceback (most recent call last):
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/ext-libs/win32ctypes/core/__init__.py", line 15, in 
    import cffi
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'cffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/__init__.py", line 24, in classFactory
    from .giscube_admin import GiscubeAdmin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/giscube_admin.py", line 17, in 
    from .backend import Giscube
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/backend/__init__.py", line 6, in 
    from .giscube import Giscube
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/backend/giscube.py", line 7, in 
    import keyring
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/keyring/__init__.py", line 6, in 
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 148, in 
    init_backend()
  File "/usr/lib/python3/dist-packages/keyring/core.py", line 64, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python3/dist-packages/keyring/util/__init__.py", line 20, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 179, in get_all_keyring
    _load_backends()
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 139, in _load_backends
    list(map(_load_backend, backends))
  File "/usr/lib/python3/dist-packages/keyring/backend.py", line 131, in _load_backend
    mod = importlib.import_module('.'+name, package)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/keyring/backends/Windows.py", line 12, in 
    from win32ctypes import pywintypes
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/ext-libs/win32ctypes/pywintypes.py", line 9, in 
    from win32ctypes.pywin32.pywintypes import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/ext-libs/win32ctypes/pywin32/__init__.py", line 11, in 
    from win32ctypes.pywin32 import win32api
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/ext-libs/win32ctypes/pywin32/win32api.py", line 12, in 
    from win32ctypes.core import _common, _kernel32, _backend
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/ext-libs/win32ctypes/core/__init__.py", line 17, in 
    from .ctypes import _advapi32, _common, _kernel32
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/copying/.local/share/QGIS/QGIS3/profiles/default/python/plugins/giscube-admin-qgis-plugin/ext-libs/win32ctypes/core/ctypes/_advapi32.py", line 12, in 
    from ctypes.wintypes import (
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.6/ctypes/wintypes.py", line 20, in 
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported
```

</details>

**Pull request merged**
